[package]
name = "character_generator"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = { version = "^0.4.1", features = ["serde"]}
sled = "0.34.7"
serde = { version = "1.0", features = ["derive"]}
serde_cbor = "0.11.2"